version: '3.8'

services:
  # PHP-FPM für die Anwendung
  app:
    image: php:8.1-fpm
    container_name: bank_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - bank-network
    depends_on:
      - database
    command: >
      bash -c "docker-php-ext-install pdo pdo_mysql mysqli &&
               php-fpm"

  # Nginx Webserver
  webserver:
    image: nginx:alpine
    container_name: bank_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
    networks:
      - bank-network

  # MySQL Datenbank
  database:
    image: mysql:8.0
    container_name: bank_database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Gloessner1!
      MYSQL_DATABASE: bank_transactions
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: Gloessner1!
    volumes:
      - bank_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bank-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pGloessner1!"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bank_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Gloessner1!
    depends_on:
      - database
    networks:
      - bank-network

volumes:
  bank_data:

networks:
  bank-network:
    driver: bridge